// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthHeader: typeof import('./components/AuthHeader.vue')['default']
    BlackWhiteLogo: typeof import('./components/icons/logos/BlackWhiteLogo.vue')['default']
    Box: typeof import('./components/Box.vue')['default']
    BrainLogo: typeof import('./components/icons/logos/BrainLogo.vue')['default']
    ColumnsGapIcon: typeof import('./components/icons/sidebar/ColumnsGapIcon.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    CustomSelect: typeof import('./components/form/selects/CustomSelect.vue')['default']
    DtmIcon: typeof import('./components/icons/sidebar/DtmIcon.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Footer: typeof import('./components/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LocaleSwitcher: typeof import('./components/LocaleSwitcher.vue')['default']
    NotesIcon: typeof import('./components/icons/sidebar/NotesIcon.vue')['default']
    PaymentServices: typeof import('./components/dropdowns/PaymentServices.vue')['default']
    PeopleRoundedIcon: typeof import('./components/icons/sidebar/PeopleRoundedIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SwordsIcon: typeof import('./components/icons/sidebar/SwordsIcon.vue')['default']
    Table: typeof import('./components/Table.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
  }
}

export {}
